version: '3.8'

services:
  maps-scraper:
    build: .
    container_name: maps-scraper
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5900:5900"  # Puerto VNC para depuración visual
    environment:
      - HEADLESS=false
      - PORT=8000
      - HOST=0.0.0.0
      - DISPLAY=:0
      - LOG_LEVEL=INFO  # Nivel de logging
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G