version: '3.8'

services:
  maps-scraper:
    build: .
    container_name: maps-scraper
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HEADLESS=true
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G